# Generated by Django 4.1.4 on 2022-12-15 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='digital',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
